version: '{build}'
skip_tags: true
clone_depth: 30

environment:
  JAVA_HOME: C:\Program Files\Java\jdk11

install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven\apache-maven-3.8.4" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'https://dlcdn.apache.org/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.zip',
          'C:\maven-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
  - cmd: SET PATH=C:\maven\apache-maven-3.8.4\bin;%JAVA_HOME%\bin;%PATH%

build_script:
  - mvn clean install -B -DskipTests

test_script:
  - mvn test -B -Dskip.systests=true --fail-at-end
  - mvn verify -pl systests/protocol-tests-amqp-1-0,systests/protocol-tests-amqp-0-8,systests/protocol-tests-amqp-0-10 -Dskip.unittests=true -B --fail-at-end

on_failure:
  - ps: |
      7z a -r surefire-reports.zip '**\target\surefire-reports\*'
      Push-AppveyorArtifact surefire-reports.zip -DeploymentName 'Surefire Reports'

on_finish:
  - ps: |
      $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
      $wc = New-Object 'System.Net.WebClient'
      $dirs = Get-ChildItem -Filter surefire-reports -Recurse
      ForEach ($dir in $dirs)
      {
        $files = Get-ChildItem -Path $dir.FullName -Filter TEST-*.xml
        ForEach ($file in $files)
        {
          $wc.UploadFile($url, (Resolve-Path $file.FullName))
        }
      }

cache:
  - C:\maven\apache-maven-3.8.4
